// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD13gsRC6uuJsrUOVvmxj2NIXTtgs9s0AA',
    appId: '1:821247315081:web:7fcf5073738b9854b88a58',
    messagingSenderId: '821247315081',
    projectId: 'finalproject-437f1',
    authDomain: 'finalproject-437f1.firebaseapp.com',
    storageBucket: 'finalproject-437f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbjUO23OgdJF3fR-CB8i-qTlAZRIaaTTQ',
    appId: '1:821247315081:android:d2191a455a7eadc6b88a58',
    messagingSenderId: '821247315081',
    projectId: 'finalproject-437f1',
    storageBucket: 'finalproject-437f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Luo34WA1posIRMnu16_fxGjUoK_uE1A',
    appId: '1:821247315081:ios:b14140a1bf95b795b88a58',
    messagingSenderId: '821247315081',
    projectId: 'finalproject-437f1',
    storageBucket: 'finalproject-437f1.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Luo34WA1posIRMnu16_fxGjUoK_uE1A',
    appId: '1:821247315081:ios:b14140a1bf95b795b88a58',
    messagingSenderId: '821247315081',
    projectId: 'finalproject-437f1',
    storageBucket: 'finalproject-437f1.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD13gsRC6uuJsrUOVvmxj2NIXTtgs9s0AA',
    appId: '1:821247315081:web:80ee324194405bffb88a58',
    messagingSenderId: '821247315081',
    projectId: 'finalproject-437f1',
    authDomain: 'finalproject-437f1.firebaseapp.com',
    storageBucket: 'finalproject-437f1.firebasestorage.app',
  );
}
